### PR TITLE
updates to README 

### PR DESCRIPTION
**Pull request by nshanbhag20001412**
Completed issue #2

### CODE REVIEW

**Comment by abhir9** [comment]
@nshanbhag20001412  great , a few minor updates
1. can we have screenshot with same screensize or dimention
2. plz fix  the last row as well

**Comment by nshanbhag20001412** [comment]
> @nshanbhag20001412 great , a few minor updates
> 
> 1. can we have screenshot with same screensize or dimention
> 2. plz fix  the last row as well
> 3. rebase as well due to other PR already get merged

can you tell me how to rebase everything?

**Comment by nshanbhag20001412** [comment]
can you tell me how to rebase everything?

**Comment by abhir9** [comment]
@nshanbhag20001412 check this out https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by abhir9** [comment]
@nshanbhag20001412 your PR #14  get merged, closing the old one #13

**Pull request closed without merging**
