### PR TITLE
Login page screenshot : mobile view

### PR DESCRIPTION
**Pull request by nshanbhag20001412**

### CODE REVIEW

**Comment by abhir9** [comment]
@nshanbhag20001412 
could you please add mobile screenshot in new coloumn, instead same screenshot, it won't look bad

**Review by abhir9 — CHANGES_REQUESTED** [review]
@nshanbhag20001412  please add separate coloumn for mobile screen shot in readme.md, so it won't look bad

**Comment by nshanbhag20001412** [comment]
> @nshanbhag20001412 please add separate coloumn for mobile screen shot in readme.md, so it won't look bad

okay will do

**Comment by nshanbhag20001412** [comment]
> @nshanbhag20001412 do you want to keep reopened ?

i completed the necessary changed. i pushed the code on the forked repo. how to update the chnages? new pull requets?

**Comment by abhir9** [comment]
new PR opened https://github.com/LoginRadius/awesome-login-pages/pull/13
closing this

**Pull request closed without merging**
