### PR TITLE
Added mobile screenshots for pages 7-12.

### PR DESCRIPTION
**Pull request by Yash-sudo-web**
I can also do the rest if you'd assign me.Thanks!

### CODE REVIEW

**Comment by Yash-sudo-web** [comment]
Also I'd like to propose an idea, we can make different sections for dekstop screenshots and mobile screenshots, I'm currently working on it, will open another pull request once done with that.

**Comment by abhir9** [comment]
@Yash-sudo-web  please update screenshot in new coloumn instead same , so it would look good

**Comment by Yash-sudo-web** [comment]
Okay ,yes I'm working on the same

**Comment by abhir9** [comment]
@Yash-sudo-web , please take latest rebase before doing your chagnes , make sure changes are alingn with existing changes

**Pull request closed without merging**
