### PR TITLE
new login page v14

### LINKED ISSUE #1: Add New login pages

### PR DESCRIPTION
**Pull request by herkura**
Just a new version of a login/sign-up page. I have uploaded a video in a md file for reference to what I have uploaded. Kindly check and update if any improvements are required from my side 😄.

### CODE REVIEW

**Review by abhir9 — APPROVED** [review]

**Comment by abhir9** [comment]
@herkura  congrats your PR merged

to win more attractive swags from loginradius, please fill this form .
https://docs.google.com/forms/d/e/1FAIpQLSfnwWUWlRRwZpgmOX7X8lGMKotLbVe1JXCjPFSahLxLWugwig/viewform

**Comment by herkura** [comment]
@abhir9 Thanks a lot!! 😄

**Comment by herkura** [comment]
Happy to contribute here

**Comment by abhir9** [comment]
@herkura  most welcome, don't forget to star the repo.

**Comment by herkura** [comment]
sure

**Comment by herkura** [comment]
@pareek-narendra @abhir9  Can you please update me about the swag?

**Comment by herkura** [comment]
@pareek-narendra @abhir9 Can you please update me about the swag? I have filled the google form for all the details regarding swag

**Comment by pareek-naren** [comment]
@herkura 
We are in the progress to dispatch the swags and it has taken time due to the huge number of contributions to our repos.
You'll get yours in the next month for sure.

**Comment by herkura** [comment]
Thx for the update.

**Pull request merged**
